# Generated by Django 4.2.9 on 2024-06-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("newsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="keyword",
            unique_together={("user", "keyword")},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("json_data", models.JSONField()),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="newsapp.keyword"
                    ),
                ),
            ],
        ),
    ]
