# Generated by Django 4.2.9 on 2024-06-28 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsapp", "0002_alter_keyword_unique_together_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="json_data",
            new_name="articles_list",
        ),
    ]
